monitor = ,preferred,auto,1
auto_reload = false

$mod      = SUPER
$terminal = kitty
$browser  = firefox


exec-once = hyprpaper
exec-once = hypridle
exec-once = quickshell -c ~/.config/quickshell
exec-once = wlsunset -l 52.48 -L 13.43

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 1
    accel_profile = flat
}

general {
    gaps_in = 2
    gaps_out = 6
    border_size = 2
    col.active_border   = rgba(88c0d0ff)
    col.inactive_border = rgba(444444aa)
    layout = dwindle
}

decoration {
    rounding = 6
    }
animations {
    enabled = yes
    animation = windows, 1, 3, default, popin
    animation = fade, 1, 2, default
    animation = workspaces, 1, 3, default, slide

}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/env.conf

misc {
disable_hyprland_logo = true
      disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true
    vfr = true
}
bindl = ,switch:off:Lid Switch, exec, ~/.config/hypr/lid.sh open
bindl = ,switch:on:Lid Switch, exec, ~/.config/hypr/lid.sh close

